### ISSUE TITLE
Help with implementing custom widget

### ISSUE THREAD

**Issue by lukors** [PistonDevelopers/conrod#1029]
I'm having some trouble implementing a custom widget.

What I'm trying to do as a first step is copy over the `circular_button` module from the custom widget example and get it to compile in my own project.

Here is the error I'm getting:
```
error[E0405]: cannot find trait `Common` in module `_conrod::widget`
  --> src\main.rs:10:14
   |
10 |     #[derive(WidgetCommon)]
   |              ^^^^^^^^^^^^ not found in `_conrod::widget`
```

Here is my main.rs:
```rust
#[macro_use]
extern crate conrod_derive;
extern crate conrod;

fn main() {}

mod circular_button {
    use conrod::widget;

    #[derive(WidgetCommon)]
    pub struct CircularButton<'a> {
        #[conrod(common_builder)]
        common: widget::CommonBuilder,
    }
}
```

Here is my Cargo.toml:
```toml
[package]
name = "bug"
version = "0.1.0"
authors = ["Lukas Orsvärn <lukas@orsvarn.com>"]

[dependencies]
conrod = { version = "0.53.0", features = ["glium", "winit"] }
conrod_derive = "0.1.0"

[features]
default = []
```
I can find the `Common` trait in `conrod::widget`, and it's public, but why can't the compiler find it?
